# Generated by Django 2.1.7 on 2019-03-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000, verbose_name='Цена')),
                ('height', models.FloatField(verbose_name='Высота стебля (м)')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='FlowerTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тип цветка')),
            ],
        ),
        migrations.AddField(
            model_name='flower',
            name='type_flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.FlowerTypes'),
        ),
    ]
